apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: multi-host-ingress
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - app.projectask.online
      secretName: multi-host-tls
  rules:
    - host: app.projectask.online
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-vue
                port:
                  number: 80

